### PR TITLE
Setup submodules

### PR DESCRIPTION
**Pull request by grawlinson**
Initial setup of using submodules for external dependencies (in this case, miniz).

So that we can point at `.gitmodules` and say "that's where we're getting them from!"

Documentation & CI will need to be fixed prior to merging this, if the PR is found acceptable.

Other stuff:

* More unused source code was ~~dragged kicking and screaming to the trash compactor~~ removed.
* Found & fixed some compiler warnings when using clang to compile the project.

### CODE REVIEW

**Comment by grawlinson** [comment]
Other external resources I'd like to add as submodules:

* SDL2 & SDL2_image (for static linking on macOS)
* x264 & ffmpeg (for videotool)

**Comment by ahockersten** [comment]
I think there needs to be a `git submodules init` step or something added to build instructions in the README? It's been a while since I used submodules. Other than that it looks good to me, so feel free to merge.

**Comment by grawlinson** [comment]
Yup, I’ll be working on the documentation tomorrow (2230 atm 😴)

**Comment by ahockersten** [comment]
I added some documentation (and added config for Visual Studio 2022 since apparently it wasn't all checked in). Merging since I may want to make other changes today that could conflict with this.

**Pull request merged**
